services:
  app:
    build: .
    container_name: chatbot_system
    restart: always
    ports:
      - "80:8000"  # Веб-панель будет доступна на 80 порту (просто по IP сервера)
    env_file:
      - .env
    volumes:
      - ./data.db:/chatbot-web-app/data.db  # Монтируем конкретный файл базы